apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: biz-platform
  app.kubernetes.io/environment: dev
resources:
  - ../../namespaces.yaml
  - ../../integration/healthz.yaml
  - ../../ingress/nginx-ingress.yaml
patches:
  - target:
      kind: Ingress
      name: api-gateway
      namespace: integration
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.dev.example.com
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.dev.example.com
      - op: replace
        path: /spec/tls/0/secretName
        value: api-dev-tls
