apiVersion: 1
datasources:
  - name: KPIs-Postgres
    type: postgres
    access: proxy
    isDefault: false
    editable: true
    url: ${KPIS_PG_HOST:postgres.svc.cluster.local}:5432
    database: ${KPIS_PG_DB:analytics}
    user: ${KPIS_PG_USER:analytics}
    secureJsonData:
      password: ${KPIS_PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false


