# Camunda 8 (helm chart: camunda/camunda-platform)
global:
  ingress:
    enabled: true
    className: nginx
    host: camunda.example.com
    tls:
      enabled: false
optimize:
  enabled: true
operate:
  enabled: true
tasklist:
  enabled: true
zeebe:
  clusterSize: 2
  partitionCount: 2
  replicationFactor: 2


