---
collections:
  - name: kubernetes.core
    version: "2.4.0"
  - name: community.docker
    version: "3.4.0"
  - name: community.general
    version: "9.0.0"

roles:
  - name: geerlingguy.docker
    version: "7.0.0"
  - name: geerlingguy.kubernetes
    version: "3.0.0"


