apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: connect
          image: confluentinc/cp-kafka-connect:7.6.0
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: biz-kafka-kafka-bootstrap.integration.svc.cluster.local:9092
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: kafka-connect
            - name: CONNECT_GROUP_ID
              value: connect-cluster
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: connect-configs
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: connect-offsets
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: connect-status
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.converters.StringConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_LOG4J_LOGGERS
              value: org.reflections=ERROR
            - name: CONNECT_PLUGIN_PATH
              value: /usr/share/java,/etc/kafka-connect/jars
          volumeMounts:
            - name: plugins
              mountPath: /etc/kafka-connect/jars
      volumes:
        - name: plugins
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: integration
spec:
  selector:
    app: kafka-connect
  ports:
    - port: 8083
      targetPort: 8083
      name: http
