configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: biz-datalake-backups
      config:
        region: us-east-1
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: us-east-1
# Azure ejemplo:
# configuration:
#   backupStorageLocation:
#     - name: default
#       provider: azure
#       bucket: velero
#       config:
#         resourceGroup: rg-biz-automation-dev
#         storageAccount: stbizautodev
#         subscriptionId: 00000000-0000-0000-0000-000000000000

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=CHANGEME
      aws_secret_access_key=CHANGEME

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.8.2
    volumeMounts:
      - mountPath: /target
        name: plugins

snapshotsEnabled: true
